# Workflow for testing that the code of incoming pull requests builds and passes tests

name: Linter Check

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  tests:
    name: Run Linter
    runs-on: ubuntu-latest
    steps:
      - name: Check out pull request
        uses: actions/checkout@v2
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-pr-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-nightly-
            ${{ runner.os }}-maven-deploy-
      - name: Set up Java and Maven
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build classes
        run: mvn clean install -B -Dmaven.test.skip=true # Just need the classes for checker use, no test necessary
      - name: Run linter/checker
        run: mvn compile -B -P lint,strict